# coding=utf-8
import requests
import re
import os
import time
from urllib.parse import urlparse
from concurrent.futures import ThreadPoolExecutor, as_completed

# --- 1. 配置区 ---
GH_TOKEN = os.getenv("GH_TOKEN", "")

GH_QUERIES = [
   
    ' "sub?target=clash" extension:yaml ',
    ' "api/v1/client/subscribe?token=" extension:yaml ',
    ' path:sub filename:*.yaml "http" ',
    ' "nodes" AND "http" extension:yaml ',
    ' "订阅地址" extension:md ',
    ' filename:sub_all.yaml ',
    ' filename:sub.yaml "clash" ',
    ' filename:subscribe.md "http" "token" ',
    ' "clash订阅" extension:yaml ',
    ' filename:valid-domains.txt ',
    ' "api/v1/client/subscribe?token=" extension:txt ',
    ' "v2board" AND "sub=" extension:py ',
    ' "sspanel" AND "/link/" extension:md ',
    ' "机场" AND "订阅" extension:txt ',
    ' "nodes" AND "https" extension:yaml ',
    ' "clash" AND "proxies" AND "url" extension:yaml ',
    ' "v2ray" AND "vmess://" extension:txt ',
    ' filename:config.yaml "Proxy Group" ',
    ' "/api/v1/client/subscribe" ',
    ' "sub_url" AND "token" extension:json ',

    ' "/api/v1/client/subscribe?token=" extension:php ', 
    ' "/sub?target=clash&url=" ',                       
    ' filename:config.json "outbounds" AND "selector" ',
    ' "proxy-providers" AND "http" extension:yaml ',    
    ' "vmess://" AND "remark" extension:txt fork:false ', 
    ' filename:.env "SUB_URL=" '                        
]

# 1.2 排除关键词列表
EXCLUDE_KEYWORDS = [
    "louwangzhiyu", "yywhale", "nxxbbf", "slianvpn", "cloudaddy", "quickbeevpn",
    "tianmiao", "cokecloud", "boluoidc", "gpket", "fast8888", "ykxqn",
    "127.0.0.1", "localhost", "github", "google", "tencent", "apple", "cloudfront",
    "w3.org", "telegram.org", "t.me", "wikipedia", "pypi", "docker", "example",
    "microsoft", "facebook", "twitter", "jsvini", "v2cross", "vercel.app", "netlify.app",
    "glpat-", "ghp_", "gho_", "ghu_", "ghs_", "ghr_", "rulesets", "subconverter",
    "baidu", "aliyun", "beian", "gov.cn", "crashlytics", "sentry.io", "umeng.com", 
    "ampproject", "schema.org", "wordpress.org", "gravatar.com", "jquery.com",
    "cloudfront.net", "akamaized.net", "azureedge.net", "fastly.net","fast8888",
    "v2ray.com", "clash.wiki", "shadowsocks.org", "getbootstrap.com"
]

# 1.3 静态资源后缀
STATIC_SUFFIXES = (
    ".jpg", ".jpeg", ".png", ".gif", ".svg", ".css", ".js", ".ico", 
    ".woff", ".woff2", ".zip", ".rar", ".exe", ".dmg", ".mp4", ".pdf"
)

# 1.4 订阅链接特征
SUB_PATTERNS = [
    "token=", "sub=", "/sub?", "/sub/", "subscribe=", "/subscribe?", 
    "api/v1/client/subscribe", "api/v1/client/sub", "/s/",
    "/link/", "/api/v1/subscribe", "/getsub", "type=clash", "type=v2ray",
    "&flag=clash", "&flag=v2ray", "clash=1", "sub/subscribe"
]

# 1.5 TG 频道源
TG_CHANNELS = [
"https://t.me/s/v2board_share", "https://t.me/s/free_v2board", "https://t.me/s/v2board_channel",
"https://t.me/s/v2ray_free_dy", "https://t.me/s/v2board_dy", "https://t.me/s/v2ray_free_clash",
"https://t.me/s/clash_v2board", "https://t.me/s/Jichang_Share", "https://t.me/s/vpn_free_link",
"https://t.me/s/nodes_share", "https://t.me/s/v2ray_free_nodes", "https://t.me/s/free_jichang_share",
"https://t.me/s/jichang_shiyong", "https://t.me/s/free_node_channel", "https://t.me/s/jichang_list", 
"https://t.me/s/v2ray_configs_pool",
"https://t.me/s/IP_CF_Config",
"https://t.me/s/FreakConfig",
"https://t.me/s/oneclickvpnkeys",
"https://t.me/s/PrivateVPNs",
"https://t.me/s/DirectVPN",
"https://t.me/s/VlessConfig",
"https://t.me/s/manVPN",
"https://t.me/s/ELiV2RAY",
"https://t.me/s/Outline_Vpn",
"https://t.me/s/PPT_f66_zHk2ZDY8",
"https://t.me/s/V2rayNGX",
"https://t.me/s/ccbaohe",
"https://t.me/s/wangcai_8",
"https://t.me/s/vpn_3000",
"https://t.me/s/academi_vpn",
"https://t.me/s/dingyue_center",
"https://t.me/s/freedatazone1",
"https://t.me/s/freev2rayi",
"https://t.me/s/mypremium98",
"https://t.me/s/inikotesla",
"https://t.me/s/v2rayngalpha",
"https://t.me/s/v2rayngalphagamer",
"https://t.me/s/jiedian_share",
"https://t.me/s/vpn_mafia",
"https://t.me/s/dr_v2ray",
"https://t.me/s/allv2board",
"https://t.me/s/bigsmoke_config",
"https://t.me/s/vpn_443",
"https://t.me/s/prossh",
"https://t.me/s/mftizi",
"https://t.me/s/qun521",
"https://t.me/s/v2rayng_my2",
"https://t.me/s/go4sharing",
"https://t.me/s/trand_farsi",
"https://t.me/s/vpnplusee_free",
"https://t.me/s/freekankan",
"https://t.me/s/awxdy666",
"https://t.me/s/dingyue_Center",
"https://t.me/s/pgkj666",
"https://t.me/s/anranbp",
"https://t.me/s/hkaa0",
"https://t.me/s/wxgqlfx",
"https://t.me/s/freeVPNjd",
"https://t.me/s/arzhecn",
"https://t.me/s/schpd",
"https://t.me/s/jichang_list",
"https://t.me/s/linux_do_channel",
"https://t.me/s/nodeseekc",
"https://t.me/s/hostloc_pro",
"https://t.me/s/serveruniverse",
"https://t.me/s/sharecentrepro",
"https://t.me/s/Impart_Cloud",
"https://t.me/s/helingqi",
"https://t.me/s/AI_News_CN",
"https://t.me/s/Newlearner",
"https://t.me/s/DocOfCard",
"https://t.me/s/baipiao_ml",
"https://t.me/s/jichangtuijian",
"https://t.me/s/Airport_News",
"https://t.me/s/freemason6",
"https://t.me/s/jichangbaipiao",
"https://t.me/s/v2free666",
"https://t.me/s/v2rayfree",
"https://t.me/s/mianfeifq",
"https://t.me/s/SSR_V2RAY_Clash",
"https://t.me/s/free_v2ray",
"https://t.me/s/node_share",
"https://t.me/s/freenode_all",
"https://t.me/s/baipiaonote",
"https://t.me/s/Jichang_Store",
"https://t.me/s/VPNOff",
"https://t.me/s/jichang0",
"https://t.me/s/V2List",
"https://t.me/s/ssr_clash_v2ray",
"https://t.me/s/Clash_Node_Share",
"https://t.me/s/free_jichang",
"https://t.me/s/GetFreeNode",
"https://t.me/s/v2ray_vpn_free",
"https://t.me/s/v2ray_free_config",
"https://t.me/s/vpn_node_share",
"https://t.me/s/Free_Config_Sharing",
"https://t.me/s/v2ray_sub_share",
"https://t.me/s/free_sub_links",
"https://t.me/s/Clash_Config",
"https://t.me/s/v2ray_pool",
"https://t.me/s/free_node_sharing",
"https://t.me/s/v2ray_nodes_free",
"https://t.me/s/jichang_bp",
"https://t.me/s/sub_share_center",
"https://t.me/s/ss_v2ray_ssr_clash",
"https://t.me/s/daily_free_nodes",
"https://t.me/s/proxy_sharing",
"https://t.me/s/fast_v2ray",
"https://t.me/s/free_internet_news",
"https://t.me/s/node_collection",
"https://t.me/s/clash_v2ray_ssr_nodes",
"https://t.me/s/v2ray_helper",
"https://t.me/s/free_proxy_list",
"https://t.me/s/open_v2ray",
"https://t.me/s/clash_sub",
"https://t.me/s/v2ray_best",
"https://t.me/s/node_king",
"https://t.me/s/free_server_list",
"https://t.me/s/v2ray_pro_free",
"https://t.me/s/jichang_report",
"https://t.me/s/free_node_daily",
"https://t.me/s/v2ray_world",
"https://t.me/s/univstar",
"https://t.me/s/iosfulishare",
"https://t.me/s/kxswa",
"https://t.me/s/vpnhat",
"https://t.me/s/baipiao01",
"https://t.me/s/allporter",
"https://t.me/s/miaomua",
"https://t.me/s/jokersfantastichome",
"https://t.me/s/TGxChina",
"https://t.me/s/wbnet",
"https://t.me/s/Jsnzk",
"https://t.me/s/gulaiguq_baipiao2",
"https://t.me/s/iunsw",
"https://t.me/s/fffffx2",
"https://t.me/s/maxshare",
"https://t.me/s/bamboo_vpn",
"https://t.me/s/baipiaob",
"https://t.me/s/airproxies",
"https://t.me/s/asjdxm",
"https://t.me/s/yaney_01",
"https://t.me/s/v2list",
"https://t.me/s/freev2rays",
"https://t.me/s/vmess_tg",
"https://t.me/s/ssrList",
"https://t.me/s/app_jiedian",
"https://t.me/s/wxdy666",
"https://t.me/s/jcvpn",
"https://t.me/s/share_proxy_001",
"https://t.me/s/zyfxlnn",
"https://t.me/s/ShareCentrePro",
"https://t.me/s/TG_2345",
"https://t.me/s/zqfxpd",
"https://t.me/s/BmFt1",
"https://t.me/s/aifenxiang2020",
"https://t.me/s/p2psharing",
"https://t.me/s/sharingnode",
"https://t.me/s/v2raydailyupdate",
"https://t.me/s/baipiaowansui",
"https://t.me/s/juzibaipiao",
"https://t.me/s/murandepindao",
"https://t.me/s/aries_init",
"https://t.me/s/forwardv2ray",
"https://t.me/s/xiaoxinv",
"https://t.me/s/bpjzx2",
"https://t.me/s/qwjhfx",
"https://t.me/s/ltscxk",
"https://t.me/s/aiuvpn",
"https://t.me/s/jiedian24",
"https://t.me/s/Free166",
"https://t.me/s/baipiaojiedian",
"https://t.me/s/changfengchannel",
"https://t.me/s/freeshadowsock",
"https://t.me/s/onessr",
"https://t.me/s/ShadowsocksRssr",
"https://t.me/s/ShareCentre",
"https://t.me/s/ssrshares",
"https://t.me/s/SSRSUB",
"https://t.me/s/vpnchina",
"https://t.me/s/suyucom",
"https://t.me/s/freeyule",
"https://t.me/s/vpn880",
"https://t.me/s/plus8889",
"https://t.me/s/ZDYZ2",
"https://t.me/s/ARv2ray",
"https://t.me/s/Alfred_Config",
"https://t.me/s/Baraye_azadi_Info",
"https://t.me/s/Capital_NET",
"https://t.me/s/Capoit",
"https://t.me/s/CloudCityy",
"https://t.me/s/ConfigV2rayNG",
"https://t.me/s/Configforvpn01",
"https://t.me/s/ConfigsHUB2",
"https://t.me/s/DailyV2RY",
"https://t.me/s/DigiV2ray",
"https://t.me/s/Easy_Free_VPN",
"https://t.me/s/Eleven_vpn",
"https://t.me/s/EliV2ray",
"https://t.me/s/EuServer",
"https://t.me/s/EzNett",
"https://t.me/s/FOXNT",
"https://t.me/s/FProxies",
"https://t.me/s/FalconPolV2rayNG",
"https://t.me/s/FreeV2rays",
"https://t.me/s/FreeVlessVpn",
"https://t.me/s/Free_HTTPCustom",
"https://t.me/s/Helix_Servers",
"https://t.me/s/Hope_Net",
"https://t.me/s/IBV2RAY",
"https://t.me/s/IRANVPNNET",
"https://t.me/s/JiedianSsr",
"https://t.me/s/Lockey_vpn",
"https://t.me/s/MTConfig",
"https://t.me/s/MrV2Ray",
"https://t.me/s/MsV2ray",
"https://t.me/s/NIM_VPN_ir",
"https://t.me/s/Napsternetvirani",
"https://t.me/s/NetAccount",
"https://t.me/s/OKAB3_Script_Channel",
"https://t.me/s/OutlineVpnOfficial",
"https://t.me/s/Powerful1VPN",
"https://t.me/s/ProxyFn",
"https://t.me/s/Qv2rayDONATED",
"https://t.me/s/Qv2raychannel",
"https://t.me/s/ServerNett",
"https://t.me/s/ShadowProxy66",
"https://t.me/s/Shh_Proxy",
"https://t.me/s/TLS_v2ray",
"https://t.me/s/TVCminer",
"https://t.me/s/UnlimitedDev",
"https://t.me/s/V2RayTz",
"https://t.me/s/V2Ray_FreedomIran",
"https://t.me/s/V2pedia",
"https://t.me/s/V2rayCollectorDonate",
"https://t.me/s/V2rayNG3",
"https://t.me/s/V2rayNGn",
"https://t.me/s/V2ray_Alpha",
"https://t.me/s/V2rayng_Fast",
"https://t.me/s/VPNCUSTOMIZE",
"https://t.me/s/V_2rayngVpn",
"https://t.me/s/ViPVpn_v2ray",
"https://t.me/s/VmessProtocol",
"https://t.me/s/WeePeeN",
"https://t.me/s/WomanLifeFreedomVPN",
"https://t.me/s/YtTe3la",
"https://t.me/s/abra_vpn",
"https://t.me/s/accountplanetir",
"https://t.me/s/adamak_vpn",
"https://t.me/s/afv2ray",
"https://t.me/s/ahe_vpn",
"https://t.me/s/ailumao",
"https://t.me/s/alfred_config",
"https://t.me/s/alienvpn402",
"https://t.me/s/alismartvpn",
"https://t.me/s/aliyosgraphy",
"https://t.me/s/alo_v2rayng",
"https://t.me/s/alpha_v2ray_fazayi",
"https://t.me/s/alphaomegavpn",
"https://t.me/s/alsheykhvpn",
"https://t.me/s/amir_rooman",
"https://t.me/s/amirinventor2010",
"https://t.me/s/amironetwork",
"https://t.me/s/an0nymousteam",
"https://t.me/s/android_best",
"https://t.me/s/angus_vpn",
"https://t.me/s/angus_vpn3",
"https://t.me/s/anix_v2ray",
"https://t.me/s/antifilterjadid",
"https://t.me/s/antifilterjadid3",
"https://t.me/s/antifilterservice",
"https://t.me/s/apkgold",
"https://t.me/s/apkprogramming",
"https://t.me/s/apple_x1",
"https://t.me/s/appsooner",
"https://t.me/s/archive_android",
"https://t.me/s/argooo_vpn",
"https://t.me/s/armod_iran",
"https://t.me/s/arouxping",
"https://t.me/s/artemis_vpn_free",
"https://t.me/s/artemisvpn1",
"https://t.me/s/arv2ra",
"https://t.me/s/arv2ray",
"https://t.me/s/asak_vpn",
"https://t.me/s/asgard_config",
"https://t.me/s/asintech",
"https://t.me/s/asliveepn",
"https://t.me/s/asr_proxy",
"https://t.me/s/astrovpn_ir",
"https://t.me/s/astrovpn_official",
"https://t.me/s/av2drup",
"https://t.me/s/axv2ray",
"https://t.me/s/azad_intrnet",
"https://t.me/s/azadneit",
"https://t.me/s/badsha_mohammad",
"https://t.me/s/bakvpns",
"https://t.me/s/bargovpn",
"https://t.me/s/bemolatext",
"https://t.me/s/berice_v2",
"https://t.me/s/bestvpn4030",
"https://t.me/s/betv2ray",
"https://t.me/s/bimnetvpn",
"https://t.me/s/birdserver",
"https://t.me/s/bitnetvpn",
"https://t.me/s/black8rose",
"https://t.me/s/blueberrynetwork",
"https://t.me/s/bluev2rayng",
"https://t.me/s/bluevpn_v2ray",
"https://t.me/s/bolbolvpn",
"https://t.me/s/bored_vpn",
"https://t.me/s/bright_vpn",
"https://t.me/s/buffalo_vpn",
"https://t.me/s/bug_vpn",
"https://t.me/s/bypass_filter",
"https://t.me/s/caa_chanel",
"https://t.me/s/caa_v2ray",
"https://t.me/s/canguro_english",
"https://t.me/s/capital_net",
"https://t.me/s/capoit",
"https://t.me/s/castom_v2ray",
"https://t.me/s/catvpns",
"https://t.me/s/cav2ray",
"https://t.me/s/cephalon_ala",
"https://t.me/s/ch_a2l",
"https://t.me/s/chanel_config",
"https://t.me/s/chatbuzzteam",
"https://t.me/s/circle_vpn",
"https://t.me/s/cisco_acc",
"https://t.me/s/click_vpnn",
"https://t.me/s/cloudcityy",
"https://t.me/s/club_vpn9",
"https://t.me/s/clubvpn443",
"https://t.me/s/cnfg_v2ray",
"https://t.me/s/cnfings",
"https://t.me/s/cod_arshiya0",
"https://t.me/s/configV2rayForFree",
"https://t.me/s/configV2rayNG",
"https://t.me/s/config_station",
"https://t.me/s/configforvpn",
"https://t.me/s/configforvpn01",
"https://t.me/s/configms",
"https://t.me/s/configpluse",
"https://t.me/s/configpositive",
"https://t.me/s/configscenter",
"https://t.me/s/configshub2",
"https://t.me/s/configsstore",
"https://t.me/s/configt",
"https://t.me/s/configv2rayforfree",
"https://t.me/s/configv2rayng",
"https://t.me/s/confing_costume",
"https://t.me/s/confing_problems",
"https://t.me/s/confingv2raayng",
"https://t.me/s/connectix",
"https://t.me/s/cpuvpn",
"https://t.me/s/croownvpn",
"https://t.me/s/custom_14",
"https://t.me/s/custom_config",
"https://t.me/s/customizev2ray",
"https://t.me/s/customv2ray",
"https://t.me/s/customvpnserver",
"https://t.me/s/dailyv2ray",
"https://t.me/s/dailyv2ry",
"https://t.me/s/damonconfig",
"https://t.me/s/daredevill_404",
"https://t.me/s/dark_telecom",
"https://t.me/s/darkma3ter24",
"https://t.me/s/darknightvpn",
"https://t.me/s/darksectora",
"https://t.me/s/darktunnelvip1",
"https://t.me/s/daryaye_sorkhh",
"https://t.me/s/dataworld_ir",
"https://t.me/s/dav2ray",
"https://t.me/s/deli_servers",
"https://t.me/s/deragv2ray",
"https://t.me/s/diamondproxytm",
"https://t.me/s/digigard_vpn",
"https://t.me/s/digiv2ray",
"https://t.me/s/directvpn",
"https://t.me/s/disvpn",
"https://t.me/s/dns68",
"https://t.me/s/donald_config",
"https://t.me/s/dribble7",
"https://t.me/s/eaglevps",
"https://t.me/s/easy_free_vpn",
"https://t.me/s/editorvpn",
"https://t.me/s/ehsawn8",
"https://t.me/s/eiiim",
"https://t.me/s/elitevpnv2",
"https://t.me/s/eliv2ray",
"https://t.me/s/energybigger_1",
"https://t.me/s/esetsecuritylicense",
"https://t.me/s/euserver",
"https://t.me/s/ev2rayy",
"https://t.me/s/evay_vpn",
"https://t.me/s/everyday_vpn",
"https://t.me/s/expreset",
"https://t.me/s/express_v2ray",
"https://t.me/s/expresspace",
"https://t.me/s/expressvpn_420",
"https://t.me/s/falconpolv2rayng",
"https://t.me/s/falcunargo",
"https://t.me/s/farahvpn",
"https://t.me/s/fasst_vpn",
"https://t.me/s/fast_2ray",
"https://t.me/s/fastfilterr",
"https://t.me/s/fastgozar",
"https://t.me/s/fazevpn",
"https://t.me/s/feri_v2ray_proxy",
"https://t.me/s/filter_vpn2",
"https://t.me/s/filterintl",
"https://t.me/s/filteroghortbede",
"https://t.me/s/filtershekan_channel",
"https://t.me/s/filtershekanssh1",
"https://t.me/s/filterzapata",
"https://t.me/s/fire_vpn_channel",
"https://t.me/s/firewallvpn",
"https://t.me/s/fix_proxy",
"https://t.me/s/flash_proxies",
"https://t.me/s/flystoreir",
"https://t.me/s/flyv2ray",
"https://t.me/s/foxnt",
"https://t.me/s/frav2ray",
"https://t.me/s/freakconfig",
"https://t.me/s/free4allVPN",
"https://t.me/s/free4allvpn",
"https://t.me/s/free_httpcustom",
"https://t.me/s/free_proxy_001",
"https://t.me/s/free_shekan",
"https://t.me/s/free_v2",
"https://t.me/s/free_v2rayyy",
"https://t.me/s/free_vpn02",
"https://t.me/s/free_worlld",
"https://t.me/s/freeconfing",
"https://t.me/s/freeinir",
"https://t.me/s/freeiranet",
"https://t.me/s/freeiranweb",
"https://t.me/s/freeland8",
"https://t.me/s/freenapsternetv",
"https://t.me/s/freenet_for_everyone",
"https://t.me/s/freenetpro99",
"https://t.me/s/freeownvpn",
"https://t.me/s/freestrongvpn",
"https://t.me/s/freev2flyng",
"https://t.me/s/freev2raym",
"https://t.me/s/freev2rayssr",
"https://t.me/s/freevlessvpn",
"https://t.me/s/freevpn3327",
"https://t.me/s/freevpnchina",
"https://t.me/s/freevpnhomesconfigs",
"https://t.me/s/frev2ray",
"https://t.me/s/frev2rayng",
"https://t.me/s/fsv2ray",
"https://t.me/s/funix_shope",
"https://t.me/s/fv2ray",
"https://t.me/s/game_file2020",
"https://t.me/s/gh_v2rayng",
"https://t.me/s/ghalagyann",
"https://t.me/s/ghalagyann2",
"https://t.me/s/global_net_vpn",
"https://t.me/s/goldd_v2ray",
"https://t.me/s/golestan_vpn",
"https://t.me/s/golf_vpn",
"https://t.me/s/good_v2rayy",
"https://t.me/s/gozargahvpn",
"https://t.me/s/gp_proxy_vpn",
"https://t.me/s/grizzlyvpn",
"https://t.me/s/hajimamadvpn",
"https://t.me/s/hajvpn",
"https://t.me/s/hatunnel_vpn",
"https://t.me/s/heinuhome",
"https://t.me/s/helix_servers",
"https://t.me/s/hennessypro",
"https://t.me/s/hermanosvpn",
"https://t.me/s/hhi_vpn222",
"https://t.me/s/hilynet",
"https://t.me/s/holderproxy",
"https://t.me/s/hologate6",
"https://t.me/s/hooshang_vpn1",
"https://t.me/s/hope_net",
"https://t.me/s/hopev2ray",
"https://t.me/s/hopevpn",
"https://t.me/s/hosseinstore_za",
"https://t.me/s/hpv2ray_official",
"https://t.me/s/hpv2rayng",
"https://t.me/s/hypervpn6",
"https://t.me/s/hypervpns",
"https://t.me/s/i3v2ray",
"https://t.me/s/ibv2ray",
"https://t.me/s/icloudyshop",
"https://t.me/s/icocoon",
"https://t.me/s/icv2ray",
"https://t.me/s/igrsdet",
"https://t.me/s/internet4iran",
"https://t.me/s/internet_nor",
"https://t.me/s/ipV2Ray",
"https://t.me/s/ip_cf_config",
"https://t.me/s/iphonebax",
"https://t.me/s/ipv2ray",
"https://t.me/s/ipv2rayng",
"https://t.me/s/ir_config_an",
"https://t.me/s/ir_nekobox",
"https://t.me/s/iran_access",
"https://t.me/s/iran_v2ray1",
"https://t.me/s/iranbaxvpn",
"https://t.me/s/iranbfilter",
"https://t.me/s/iraniv2ray",
"https://t.me/s/iranmedicalvpn",
"https://t.me/s/iranproxypro",
"https://t.me/s/iranray_vpn",
"https://t.me/s/iranv2raynng",
"https://t.me/s/iranvipnet",
"https://t.me/s/iranvpnnet",
"https://t.me/s/irn_vpn",
"https://t.me/s/irnhackers",
"https://t.me/s/iroazadi",
"https://t.me/s/irov2rayn",
"https://t.me/s/irvpnify",
"https://t.me/s/jetupnet",
"https://t.me/s/jiedianf",
"https://t.me/s/jiedianssr",
"https://t.me/s/jiujied",
"https://t.me/s/jokerv2ray",
"https://t.me/s/justkingoo",
"https://t.me/s/kafing_2",
"https://t.me/s/kesslervpn",
"https://t.me/s/khadamat_sadra",
"https://t.me/s/khalaa_vpn",
"https://t.me/s/kiava",
"https://t.me/s/kilid_stor",
"https://t.me/s/kingoclubs",
"https://t.me/s/kingofilter",
"https://t.me/s/kingofv2ray",
"https://t.me/s/kingspeedchanel",
"https://t.me/s/kralvpn",
"https://t.me/s/kurd_v2ray",
"https://t.me/s/kurdistan_vpn_perfectt",
"https://t.me/s/kurdvpn1",
"https://t.me/s/kuto_proxy",
"https://t.me/s/kuto_proxy1",
"https://t.me/s/kuto_proxy2",
"https://t.me/s/lakvpn1",
"https://t.me/s/lax_vpn",
"https://t.me/s/legendery_server",
"https://t.me/s/lepingshop",
"https://t.me/s/lepingvpn",
"https://t.me/s/lexa_vpn",
"https://t.me/s/lightning6",
"https://t.me/s/lightv2ray",
"https://t.me/s/likearzonpanell",
"https://t.me/s/limootuursh",
"https://t.me/s/lion_channel_vpn2",
"https://t.me/s/liq_vpn",
"https://t.me/s/lockey_vpn",
"https://t.me/s/lrnbymaa",
"https://t.me/s/m_buy",
"https://t.me/s/m_vipv2ray",
"https://t.me/s/mahanvpn",
"https://t.me/s/mahdiserver",
"https://t.me/s/mahxray",
"https://t.me/s/mainv2ray",
"https://t.me/s/marketvpni",
"https://t.me/s/mater_1345",
"https://t.me/s/matrixnetvvork",
"https://t.me/s/maznet",
"https://t.me/s/mdvpnsec",
"https://t.me/s/mehrosaboran",
"https://t.me/s/meli_prooxy",
"https://t.me/s/meli_proxyy",
"https://t.me/s/meli_v2rayng",
"https://t.me/s/melov2ray",
"https://t.me/s/mester_v2ray",
"https://t.me/s/mi_pn_official",
"https://t.me/s/migping",
"https://t.me/s/mikasavpn",
"https://t.me/s/mimitdl",
"https://t.me/s/miyanbor_vpn",
"https://t.me/s/mizbanv2ray",
"https://t.me/s/mobilinternet",
"https://t.me/s/mobsec",
"https://t.me/s/moein_insta",
"https://t.me/s/moft_vpn",
"https://t.me/s/moftinet",
"https://t.me/s/mr_vpn123",
"https://t.me/s/mrv2raay",
"https://t.me/s/mrv2ray",
"https://t.me/s/mrvpn1403",
"https://t.me/s/mso_666_baz",
"https://t.me/s/msv2flyng",
"https://t.me/s/msv2ray",
"https://t.me/s/msv2raynp",
"https://t.me/s/mt_team_iran",
"https://t.me/s/mtconfig",
"https://t.me/s/mtpproxy0098",
"https://t.me/s/mtproxy22_v2ray",
"https://t.me/s/mtpv2ray",
"https://t.me/s/mxv2ray",
"https://t.me/s/my_proxii",
"https://t.me/s/n2vpn",
"https://t.me/s/nameless255",
"https://t.me/s/napsternetvirani",
"https://t.me/s/nepo_v2ray",
"https://t.me/s/netaccount",
"https://t.me/s/netmaask",
"https://t.me/s/netmellianti",
"https://t.me/s/netspeedservice",
"https://t.me/s/network_cfz",
"https://t.me/s/networknim",
"https://t.me/s/new_mtproxi2",
"https://t.me/s/nicolv2ray",
"https://t.me/s/nim_vpn_ir",
"https://t.me/s/nitrovpne",
"https://t.me/s/nofilter_v2rayng",
"https://t.me/s/nofiltering2",
"https://t.me/s/noori_93",
"https://t.me/s/nordaccount1",
"https://t.me/s/novavpn1984",
"https://t.me/s/novinology",
"https://t.me/s/npv_v2ray",
"https://t.me/s/nt_safe",
"https://t.me/s/ntconfig",
"https://t.me/s/nufilter",
"https://t.me/s/nufilter2",
"https://t.me/s/oceanproo",
"https://t.me/s/ohvpn",
"https://t.me/s/optvpn",
"https://t.me/s/orb_daily",
"https://t.me/s/orb_irancell",
"https://t.me/s/orb_mci",
"https://t.me/s/orb_rightel",
"https://t.me/s/orb_vpn",
"https://t.me/s/outlineOpenKey",
"https://t.me/s/outline_ir",
"https://t.me/s/outline_oneclick1",
"https://t.me/s/outline_vpn",
"https://t.me/s/outlineiran",
"https://t.me/s/outlinev2rayng",
"https://t.me/s/outlinevpnofficial",
"https://t.me/s/ovpn2",
"https://t.me/s/oxidvip",
"https://t.me/s/oxir_vpn",
"https://t.me/s/oxnet_ir",
"https://t.me/s/pak4you",
"https://t.me/s/pardazeshvpn",
"https://t.me/s/parsashonam",
"https://t.me/s/payam_nsi",
"https://t.me/s/persian_proxy6",
"https://t.me/s/persianv2rayng",
"https://t.me/s/ph_onex",
"https://t.me/s/phiilshekn",
"https://t.me/s/piavpngo",
"https://t.me/s/pin_proxy",
"https://t.me/s/ping01pro",
"https://t.me/s/polproxy",
"https://t.me/s/ponv2ray",
"https://t.me/s/pov2ray",
"https://t.me/s/powerful1vpn",
"https://t.me/s/ppal03",
"https://t.me/s/premiumaccshoop",
"https://t.me/s/prim_vpn",
"https://t.me/s/private_access_guard_vpn",
"https://t.me/s/privatevpnn",
"https://t.me/s/privatevpns",
"https://t.me/s/pro_chaneel",
"https://t.me/s/programmer_best",
"https://t.me/s/proprojec",
"https://t.me/s/proxie",
"https://t.me/s/proxiiraniii",
"https://t.me/s/proxiteiegramm",
"https://t.me/s/proxy48",
"https://t.me/s/proxy_iranv2",
"https://t.me/s/proxy_mtm",
"https://t.me/s/proxy_mtproto_vpns_free",
"https://t.me/s/proxy_n1",
"https://t.me/s/proxy_speed",
"https://t.me/s/proxycityiran",
"https://t.me/s/proxydaemioutline",
"https://t.me/s/proxyfn",
"https://t.me/s/proxyforopeta",
"https://t.me/s/proxyirancel",
"https://t.me/s/proxystore11",
"https://t.me/s/proxysudo",
"https://t.me/s/proxyymeliii",
"https://t.me/s/prrofile_purple",
"https://t.me/s/public504",
"https://t.me/s/puni_shop_v2rayng",
"https://t.me/s/pydriclub",
"https://t.me/s/qeshmserver",
"https://t.me/s/qrv2ray",
"https://t.me/s/qv2raychannel",
"https://t.me/s/radiofarex",
"https://t.me/s/rayanconf",
"https://t.me/s/raze_vpn",
"https://t.me/s/realvpnmaster",
"https://t.me/s/relaxv2ray",
"https://t.me/s/renetvpn",
"https://t.me/s/repairms",
"https://t.me/s/rez1vpn",
"https://t.me/s/rk_filtershekan",
"https://t.me/s/rk_filtershking",
"https://t.me/s/rnrifci",
"https://t.me/s/romax_vpn",
"https://t.me/s/royalping_ir",
"https://t.me/s/rxv2ray",
"https://t.me/s/s0013_Official",
"https://t.me/s/s0013_official",
"https://t.me/s/sabz_v2ray",
"https://t.me/s/saferoadnet",
"https://t.me/s/sajad_titan_s_t_n_v2ray",
"https://t.me/s/samiv2ray",
"https://t.me/s/satellitenewspersian",
"https://t.me/s/satoshivpn",
"https://t.me/s/savagev2ray",
"https://t.me/s/sayco_proxy",
"https://t.me/s/selinc",
"https://t.me/s/sellvpniran1",
"https://t.me/s/server444",
"https://t.me/s/server_nekobox",
"https://t.me/s/servermomo",
"https://t.me/s/servernett",
"https://t.me/s/serversiran11",
"https://t.me/s/serverv2ray00",
"https://t.me/s/set_v2ray",
"https://t.me/s/seven_ping",
"https://t.me/s/shadow_v2ray",
"https://t.me/s/shadowproxy66",
"https://t.me/s/shadowsockskeys",
"https://t.me/s/shadowsocksm",
"https://t.me/s/shadowsocksshop",
"https://t.me/s/share_nodes",
"https://t.me/s/shconfig",
"https://t.me/s/shh_proxy",
"https://t.me/s/shopingv2ray",
"https://t.me/s/sinabigo",
"https://t.me/s/sitefilter",
"https://t.me/s/skivpn",
"https://t.me/s/snowguardvpn",
"https://t.me/s/sobi_vpn",
"https://t.me/s/sockcs_http",
"https://t.me/s/sockshttp_vpn",
"https://t.me/s/sourcefreefilter",
"https://t.me/s/spcware",
"https://t.me/s/speed_vpn70",
"https://t.me/s/speedconfig00",
"https://t.me/s/speedent_net",
"https://t.me/s/spikevpn",
"https://t.me/s/srcvpn",
"https://t.me/s/suddaehi",
"https://t.me/s/superpinghub",
"https://t.me/s/svnteam",
"https://t.me/s/tc_v2ray",
"https://t.me/s/teamvpnpro",
"https://t.me/s/tehranargo",
"https://t.me/s/tehranargo1",
"https://t.me/s/teiknovpn",
"https://t.me/s/telmavpn",
"https://t.me/s/tenzovpn",
"https://t.me/s/thunderv2ray",
"https://t.me/s/tiktok_proxy",
"https://t.me/s/timingvpn",
"https://t.me/s/tiny_vpn_official",
"https://t.me/s/titan_v2rayvpn",
"https://t.me/s/tls_v2ray",
"https://t.me/s/tmv2ray",
"https://t.me/s/top_vpn_chanel",
"https://t.me/s/topvpn02",
"https://t.me/s/torang_vpn",
"https://t.me/s/toyota_proxy",
"https://t.me/s/toyota_proxyyyy",
"https://t.me/s/tunssh",
"https://t.me/s/turboo_server",
"https://t.me/s/tv2rayrr",
"https://t.me/s/tv_v2ray",
"https://t.me/s/u3ervpn",
"https://t.me/s/u_confingvpn",
"https://t.me/s/ultravpn_v2ray",
"https://t.me/s/unlimiteddev",
"https://t.me/s/uraniumvpn",
"https://t.me/s/v20reyng",
"https://t.me/s/v2Line",
"https://t.me/s/v2_Hub",
"https://t.me/s/v2_hub",
"https://t.me/s/v2_r_ayng",
"https://t.me/s/v2_team",
"https://t.me/s/v2ang",
"https://t.me/s/v2aryng_vpn",
"https://t.me/s/v2bamdad",
"https://t.me/s/v2boxng74",
"https://t.me/s/v2dotcom",
"https://t.me/s/v2fast100",
"https://t.me/s/v2fetch",
"https://t.me/s/v2fox_config",
"https://t.me/s/v2gng",
"https://t.me/s/v2graphy",
"https://t.me/s/v2hamid",
"https://t.me/s/v2icy",
"https://t.me/s/v2line",
"https://t.me/s/v2logy",
"https://t.me/s/v2maxx",
"https://t.me/s/v2meowcf",
"https://t.me/s/v2mod",
"https://t.me/s/v2mystery",
"https://t.me/s/v2naptv",
"https://t.me/s/v2net_iran",
"https://t.me/s/v2org",
"https://t.me/s/v2pedia",
"https://t.me/s/v2ra2",
"https://t.me/s/v2raa_server",
"https://t.me/s/v2raand",
"https://t.me/s/v2raayngconfig",
"https://t.me/s/v2rabot",
"https://t.me/s/v2rang_255",
"https://t.me/s/v2range",
"https://t.me/s/v2rangkanal",
"https://t.me/s/v2raxx",
"https://t.me/s/v2ray009",
"https://t.me/s/v2ray03",
"https://t.me/s/v2ray16",
"https://t.me/s/v2ray1_ng",
"https://t.me/s/v2ray313",
"https://t.me/s/v2ray4free",
"https://t.me/s/v2ray851403",
"https://t.me/s/v2ray8x",
"https://t.me/s/v2ray96",
"https://t.me/s/v2rayNG_VPN",
"https://t.me/s/v2rayNG_VPNN",
"https://t.me/s/v2ray_8",
"https://t.me/s/v2ray_83",
"https://t.me/s/v2ray_alpha",
"https://t.me/s/v2ray_best_iran",
"https://t.me/s/v2ray_cartel",
"https://t.me/s/v2ray_custom",
"https://t.me/s/v2ray_donya",
"https://t.me/s/v2ray_fark",
"https://t.me/s/v2ray_fd",
"https://t.me/s/v2ray_for_free",
"https://t.me/s/v2ray_freedomiran",
"https://t.me/s/v2ray_god",
"https://t.me/s/v2ray_inter",
"https://t.me/s/v2ray_ng",
"https://t.me/s/v2ray_nonoal",
"https://t.me/s/v2ray_official",
"https://t.me/s/v2ray_one1",
"https://t.me/s/v2ray_onli",
"https://t.me/s/v2ray_outlinee",
"https://t.me/s/v2ray_outlineir",
"https://t.me/s/v2ray_phoenix",
"https://t.me/s/v2ray_raha",
"https://t.me/s/v2ray_reality_new",
"https://t.me/s/v2ray_rh",
"https://t.me/s/v2ray_rolly",
"https://t.me/s/v2ray_string",
"https://t.me/s/v2ray_swhil",
"https://t.me/s/v2ray_tunnel_plus",
"https://t.me/s/v2ray_txshop",
"https://t.me/s/v2ray_ty",
"https://t.me/s/v2ray_vme",
"https://t.me/s/v2ray_vmes",
"https://t.me/s/v2ray_vpnalfa",
"https://t.me/s/v2ray_youtube",
"https://t.me/s/v2rayan",
"https://t.me/s/v2rayargon",
"https://t.me/s/v2rayarmy",
"https://t.me/s/v2rayaz",
"https://t.me/s/v2raybe",
"https://t.me/s/v2raybold",
"https://t.me/s/v2raybx",
"https://t.me/s/v2raycactus",
"https://t.me/s/v2raycollectordonate",
"https://t.me/s/v2raycrow",
"https://t.me/s/v2raycustomize",
"https://t.me/s/v2raydiyako",
"https://t.me/s/v2rayeservers",
"https://t.me/s/v2rayfa",
"https://t.me/s/v2rayfast",
"https://t.me/s/v2rayfast_7",
"https://t.me/s/v2rayfr",
"https://t.me/s/v2rayfree1",
"https://t.me/s/v2rayhubvip",
"https://t.me/s/v2rayi_net",
"https://t.me/s/v2raying",
"https://t.me/s/v2rayip1",
"https://t.me/s/v2rayir1",
"https://t.me/s/v2rayland02",
"https://t.me/s/v2rayn_openavpn",
"https://t.me/s/v2rayn_red",
"https://t.me/s/v2rayn_store",
"https://t.me/s/v2rayng110n",
"https://t.me/s/v2rayng12023",
"https://t.me/s/v2rayng20000000",
"https://t.me/s/v2rayng3",
"https://t.me/s/v2rayng8833",
"https://t.me/s/v2rayng_81",
"https://t.me/s/v2rayng_channel_vpn",
"https://t.me/s/v2rayng_fast",
"https://t.me/s/v2rayng_ip",
"https://t.me/s/v2rayng_lion",
"https://t.me/s/v2rayng_nv",
"https://t.me/s/v2rayng_ribvar",
"https://t.me/s/v2rayng_v",
"https://t.me/s/v2rayng_v2_ray",
"https://t.me/s/v2rayng_vpn",
"https://t.me/s/v2rayng_vpnn",
"https://t.me/s/v2rayng_vpnrog",
"https://t.me/s/v2rayngchaannel",
"https://t.me/s/v2rayngchannelll",
"https://t.me/s/v2rayngcloud",
"https://t.me/s/v2rayngco0",
"https://t.me/s/v2rayngconfiig",
"https://t.me/s/v2rayngconfings",
"https://t.me/s/v2rayngfast",
"https://t.me/s/v2rayngfreee",
"https://t.me/s/v2rayngg_iran",
"https://t.me/s/v2rayngim",
"https://t.me/s/v2rayngmat",
"https://t.me/s/v2rayngn",
"https://t.me/s/v2rayngninja",
"https://t.me/s/v2rayngprivate",
"https://t.me/s/v2rayngraisi",
"https://t.me/s/v2rayngrit",
"https://t.me/s/v2rayngrr13",
"https://t.me/s/v2rayngseven",
"https://t.me/s/v2rayngte",
"https://t.me/s/v2rayngtime",
"https://t.me/s/v2rayngup",
"https://t.me/s/v2rayngupp",
"https://t.me/s/v2rayngvpn",
"https://t.me/s/v2rayngvpn_1",
"https://t.me/s/v2rayngvpnn",
"https://t.me/s/v2rayngvvpn",
"https://t.me/s/v2raynplus",
"https://t.me/s/v2raynz",
"https://t.me/s/v2rayopen",
"https://t.me/s/v2raypanelhub",
"https://t.me/s/v2rayprooo",
"https://t.me/s/v2rayprotocol",
"https://t.me/s/v2raysaznv",
"https://t.me/s/v2rayshop_m",
"https://t.me/s/v2raytg",
"https://t.me/s/v2raytork",
"https://t.me/s/v2raytz",
"https://t.me/s/v2rayvmess",
"https://t.me/s/v2rayvpn009",
"https://t.me/s/v2rayvpn2",
"https://t.me/s/v2rayvpnchannel",
"https://t.me/s/v2rayvpnclub",
"https://t.me/s/v2rayvpnking0",
"https://t.me/s/v2rayweb",
"https://t.me/s/v2rayy_ir",
"https://t.me/s/v2rayy_vpn13",
"https://t.me/s/v2rayyngvpn",
"https://t.me/s/v2rayza",
"https://t.me/s/v2raz",
"https://t.me/s/v2rey_free_for_all",
"https://t.me/s/v2reyy",
"https://t.me/s/v2rez",
"https://t.me/s/v2roay",
"https://t.me/s/v2rplus",
"https://t.me/s/v2rray1_ng",
"https://t.me/s/v2rray_ng",
"https://t.me/s/v2ry_proxy",
"https://t.me/s/v2ryng01",
"https://t.me/s/v2ryorg",
"https://t.me/s/v2ryvip",
"https://t.me/s/v2safe",
"https://t.me/s/v2safee",
"https://t.me/s/v2sezar",
"https://t.me/s/v2shop2",
"https://t.me/s/v2vipchannel",
"https://t.me/s/v3410ray",
"https://t.me/s/v5ray_ng",
"https://t.me/s/v_2ray1",
"https://t.me/s/v_2rayngvpn",
"https://t.me/s/v_2rey",
"https://t.me/s/vboxpanel",
"https://t.me/s/vip_free_vpn02",
"https://t.me/s/vipnetmeli",
"https://t.me/s/vipserverstm",
"https://t.me/s/vipufovpn",
"https://t.me/s/vipv2rayngnp",
"https://t.me/s/vipv2rayngvip",
"https://t.me/s/vipv2rayvip",
"https://t.me/s/vipv2rey",
"https://t.me/s/vipvpn_v2ray",
"https://t.me/s/virapn",
"https://t.me/s/virav2ray",
"https://t.me/s/vistav2ray",
"https://t.me/s/vlees_v2rayng",
"https://t.me/s/vless_vmess",
"https://t.me/s/vlessconfig",
"https://t.me/s/vmess_ir",
"https://t.me/s/vmess_iran",
"https://t.me/s/vmessiran",
"https://t.me/s/vmesskhodam",
"https://t.me/s/vmesskhodam_vip",
"https://t.me/s/vmessorg",
"https://t.me/s/vmessprotocol",
"https://t.me/s/vp22ray",
"https://t.me/s/vpidiamond",
"https://t.me/s/vplusvpn_free",
"https://t.me/s/vpn11_v2",
"https://t.me/s/vpn4ir_1",
"https://t.me/s/vpn_098",
"https://t.me/s/vpn_315",
"https://t.me/s/vpn_Nv1",
"https://t.me/s/vpn_amo",
"https://t.me/s/vpn_arta",
"https://t.me/s/vpn_azadi_2024",
"https://t.me/s/vpn_bal0uch",
"https://t.me/s/vpn_booth",
"https://t.me/s/vpn_connect",
"https://t.me/s/vpn_famous",
"https://t.me/s/vpn_gaming",
"https://t.me/s/vpn_gold_free_1",
"https://t.me/s/vpn_ioss",
"https://t.me/s/vpn_kanfik",
"https://t.me/s/vpn_mikey",
"https://t.me/s/vpn_nafas",
"https://t.me/s/vpn_ocean",
"https://t.me/s/vpn_room",
"https://t.me/s/vpn_shop_v1",
"https://t.me/s/vpn_storm",
"https://t.me/s/vpn_tehran",
"https://t.me/s/vpn_v2ra_ng",
"https://t.me/s/vpn_v2rang_box",
"https://t.me/s/vpn_v2rayng_gap",
"https://t.me/s/vpn_v2rayng_iran",
"https://t.me/s/vpn_vetiver",
"https://t.me/s/vpn_vip_nor",
"https://t.me/s/vpn_wedbaz2",
"https://t.me/s/vpn_whal",
"https://t.me/s/vpn_xw",
"https://t.me/s/vpn_zvpn",
"https://t.me/s/vpnafra",
"https://t.me/s/vpnaiden",
"https://t.me/s/vpnandroid2",
"https://t.me/s/vpnbigbang",
"https://t.me/s/vpnclick",
"https://t.me/s/vpncostume",
"https://t.me/s/vpncostumer",
"https://t.me/s/vpncustomize",
"https://t.me/s/vpned",
"https://t.me/s/vpnepic",
"https://t.me/s/vpnfail_v2ray",
"https://t.me/s/vpnfastservice",
"https://t.me/s/vpnfree",
"https://t.me/s/vpnfreeaccounts",
"https://t.me/s/vpnfreeramoo",
"https://t.me/s/vpngate_config",
"https://t.me/s/vpnhouse_official",
"https://t.me/s/vpnhub69",
"https://t.me/s/vpnkanfik",
"https://t.me/s/vpnkar",
"https://t.me/s/vpnkaro",
"https://t.me/s/vpnmasi",
"https://t.me/s/vpnmk1",
"https://t.me/s/vpnowl",
"https://t.me/s/vpnpacket",
"https://t.me/s/vpnplus100",
"https://t.me/s/vpnpopular2023",
"https://t.me/s/vpnsal",
"https://t.me/s/vpnserver_tel",
"https://t.me/s/vpnserverrr",
"https://t.me/s/vpnshecan",
"https://t.me/s/vpnskyy",
"https://t.me/s/vpnsshocean",
"https://t.me/s/vpnstorefast",
"https://t.me/s/vpntrt",
"https://t.me/s/vpntwitt",
"https://t.me/s/vpnv2rayonline",
"https://t.me/s/vpnv2raytop",
"https://t.me/s/vpnvg",
"https://t.me/s/vpnwedbaz",
"https://t.me/s/vpnwlf",
"https://t.me/s/vpnworldone",
"https://t.me/s/vpnxyam_ir",
"https://t.me/s/vpnyes",
"https://t.me/s/vpray3",
"https://t.me/s/vtechno_vpn",
"https://t.me/s/vtworay_wolf",
"https://t.me/s/wancloudfa",
"https://t.me/s/warphiddify",
"https://t.me/s/wbrovers",
"https://t.me/s/wearestand",
"https://t.me/s/webhube",
"https://t.me/s/webovpn",
"https://t.me/s/webrovers",
"https://t.me/s/webshecan",
"https://t.me/s/weepeen",
"https://t.me/s/white_servers_turkmenistan",
"https://t.me/s/wizyvpn",
"https://t.me/s/womanlifefreedom13",
"https://t.me/s/womanlifefreedomvpn",
"https://t.me/s/world_vmess",
"https://t.me/s/wsbvpn",
"https://t.me/s/wxgmrjdcc",
"https://t.me/s/x4azadi",
"https://t.me/s/xiaobaicaifx",
"https://t.me/s/xiv2ray",
"https://t.me/s/xivpn",
"https://t.me/s/xnxv2ray",
"https://t.me/s/xray_vpn_pro",
"https://t.me/s/xrayzxn",
"https://t.me/s/xvproxy",
"https://t.me/s/yangcun68",
"https://t.me/s/yasv2ray",
"https://t.me/s/yekoyekvpn",
"https://t.me/s/ys_v2ray",
"https://t.me/s/ytte3la",
"https://t.me/s/yuproxytelegram",
"https://t.me/s/yxjnode",
"https://t.me/s/zabuza_shop",
"https://t.me/s/zar_vpn",
"https://t.me/s/zdyz2",
"https://t.me/s/zede_filteri",
"https://t.me/s/zedmodeonvpn",
"https://t.me/s/zedping",
"https://t.me/s/zen_cloud",
"https://t.me/s/zerobaipiao",
"https://t.me/s/zeynabghatee",
"https://t.me/s/zibanabz",
"https://t.me/s/zilatvpn",
"https://t.me/s/zvpnn",
"https://t.me/s/sdffnkl",
"https://t.me/s/WFVPN",
"https://t.me/s/ripaojiedian",
"https://t.me/s/TGVPN777",
"https://t.me/s/v2queen",
"https://t.me/s/jiedianxielou",
"https://t.me/s/wz2023jd",
"https://t.me/s/pgkj0402",
"https://t.me/s/freevpnatm",
"https://t.me/s/SubscriptionShare",
"https://t.me/s/sorenab1",
"https://t.me/s/crackhub_cn",
"https://t.me/s/ssrsub",
"https://t.me/s/iamdt009",
"https://t.me/s/v2rayshahin",
"https://t.me/s/DingyueJiedian8_chat",
"https://www.mibei77.com",
"https://t.me/s/changfengshare",
"https://t.me/s/freebaipiao",
"https://t.me/s/dafeiji100",
"https://t.me/s/nodesharing",
"https://t.me/s/WangCai_1",
"https://t.me/s/Hello_World_1024",
"https://t.me/s/zzzjjjkkkoi",
"https://t.me/s/mfjdpd",
"https://t.me/s/httpproxygo",
"https://t.me/s/byxiaoxi",
"https://t.me/s/jiedianF",
"https://t.me/s/clash006",
"https://t.me/s/kfyunn",
"https://t.me/s/jiuJieD",
"https://t.me/s/freetgpp",
"https://t.me/s/tyfelixna",
"https://t.me/s/socks5list",
"https://t.me/s/jimubiedao",
"https://t.me/s/daorzadannet",
"https://t.me/s/LoRd_uL4mo",
"https://t.me/s/ShadowSocks_s",
"https://t.me/s/azadi_az_inja_migzare",
"https://t.me/s/LegenderY_Servers",
"https://t.me/s/free_v2rayy",
"https://t.me/s/v2rayNG_Matsuri",
"https://t.me/s/v2freevpn",
"https://t.me/s/Jeyksatan",
"https://t.me/s/hassan_saboorii",
"https://t.me/s/v2rayNGNeT",
"https://t.me/s/lagvpn13",
"https://t.me/s/server01012",
"https://t.me/s/PAINB0Y",
"https://t.me/s/vmess_vless_v2rayng",
"https://t.me/s/VpnProSec",
"https://t.me/s/FreeIranT",
"https://t.me/s/hashmakvpn",
"https://t.me/s/X_Her0",
"https://t.me/s/Cov2ray"

]

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
}

URL_PATTERN = re.compile(r'https?://[a-zA-Z0-9\-\.]+(?::\d+)?/[^\s\'"<>\]\)\,}]+')
IP_PATTERN = re.compile(r'^(\d{1,3}\.){3}\d{1,3}(:\d+)?$')

# --- 2. 功能函数 ---

def is_valid_url(url):
    """校验 URL 是否合法"""
    if not url: return False
    _exclude = EXCLUDE_KEYWORDS
    _static = STATIC_SUFFIXES
    u_low = url.strip().rstrip('.,/').lower()
    if not u_low.startswith('http') or len(u_low) < 15 or len(u_low) > 500: 
        return False
    if any(k in u_low for k in _exclude): 
        return False
    if '{' in u_low or '$' in u_low or 'githubusercontent' in u_low: 
        return False
    path_only = u_low.split('?')[0]
    if path_only.endswith(_static):
        return False
    return True

def http_get(url, timeout=15):
    """通用的 HTTP GET 请求"""
    try:
        headers = HEADERS.copy()
        if "api.github.com" in url:
            if GH_TOKEN:
                headers["Authorization"] = f"token {GH_TOKEN}"
            headers["Accept"] = "application/vnd.github.v3+json"
        res = requests.get(url, headers=headers, timeout=timeout)
        return res if res.status_code == 200 else None
    except:
        return None

def process_github_item(item):
    """处理 GitHub 搜索到的单个文件内容"""
    links = set()
    try:
        raw_url = item.get('html_url', '').replace('github.com', 'raw.githubusercontent.com').replace('/blob/', '/')
        file_res = http_get(raw_url, timeout=10)
        if file_res:
            found = URL_PATTERN.findall(file_res.text)
            for l in found:
                clean_l = l.rstrip('.,/;\'"')
                if is_valid_url(clean_l):
                    links.add(clean_l)
    except:
        pass
    return links

def fetch_github():
    """从 GitHub 采集"""
    all_links = set()
    for q in GH_QUERIES:
        api_url = f"https://api.github.com/search/code?q={q}&sort=indexed&per_page=100"
        res = http_get(api_url)
        if not res: 
            continue
        try:
            items = res.json().get('items', [])
            print(f" -> [GitHub] 搜索关键词 '{q[:15]}...' | 命中文件: {len(items)}")
            with ThreadPoolExecutor(max_workers=10) as sub_executor:
                futures = [sub_executor.submit(process_github_item, item) for item in items]
                for f in as_completed(futures):
                    all_links.update(f.result())
        except Exception as e:
            print(f" [!] GitHub 解析异常: {e}")
            continue
        time.sleep(2) 
    return all_links

def fetch_tg():
    """从 TG 频道采集"""
    links = set()
    for url in TG_CHANNELS:
        res = http_get(url, timeout=15)
        if res:
            found = URL_PATTERN.findall(res.text)
            valid = [l.rstrip('.,/;\'"') for l in found if is_valid_url(l)]
            links.update(valid)
            if len(valid) > 0:
                print(f" -> [TG] 频道: {url.split('/')[-1]} | 获取有效 URL: {len(valid)}")
    return links

def load_existing(filename):
    """加载本地历史数据"""
    if os.path.exists(filename):
        try:
            with open(filename, "r", encoding="utf-8") as f:
                return set(line.strip() for line in f if line.strip())
        except:
            return set()
    return set()

# --- 3. 主程序 ---

if __name__ == "__main__":
    start_time = time.time()
    print(f"=== BOT 启动：开始深度采集 (时间: {time.strftime('%Y-%m-%d %H:%M:%S')}) ===")
    
    # 1. 抓取新链接
    with ThreadPoolExecutor(max_workers=2) as executor:
        f1 = executor.submit(fetch_github)
        f2 = executor.submit(fetch_tg)
        all_found = f1.result().union(f2.result())

    # 2. 增量去重逻辑（读取现有文件内容）
    old_urls = load_existing("urls.txt")
    old_subs = load_existing("subscribes.txt")

    # 创建新的集合用于存储合并后的结果
    final_urls = old_urls.copy()
    final_subs = old_subs.copy()

    for link in all_found:
        try:
            parsed = urlparse(link)
            if parsed.netloc and '.' in parsed.netloc:
                if IP_PATTERN.match(parsed.netloc): continue
                
                # 提取协议+域名
                domain_base = f"{parsed.scheme}://{parsed.netloc}"
                final_urls.add(domain_base)
                
                # 提取满足特征的订阅链接
                link_lower = link.lower()
                if any(p in link_lower for p in SUB_PATTERNS):
                    if "glpat-" not in link_lower:
                        final_subs.add(link)
        except: 
            continue

    # 3. 数据持久化 (排序并去重保存)
    try:
        # 保存域名库 (urls.txt)
        if final_urls:
            with open("urls.txt", "w", encoding="utf-8") as f:
                f.write("\n".join(sorted(list(final_urls))) + "\n")
        
        # 保存订阅库 (subscribes.txt)
        if final_subs:
            with open("subscribes.txt", "w", encoding="utf-8") as f:
                f.write("\n".join(sorted(list(final_subs))) + "\n")
                
        print(" [√] 增量去重数据已成功保存。")
    except Exception as e:
        print(f" [!] 文件写入失败: {e}")

    # 4. 统计汇报
    duration = int(time.time() - start_time)
    print("-" * 50)
    print(f"采集汇总报告 (耗时: {duration}s)")
    print(f" -> 原始发现总数: {len(all_found)} 条")
    print(f" -> 累计唯一域名(urls.txt): {len(final_urls)} (新增: {len(final_urls) - len(old_urls)})")
    print(f" -> 累计唯一订阅(subscribes.txt): {len(final_subs)} (新增: {len(final_subs) - len(old_subs)})")
    print("-" * 50)
