name: check_links
on:
  push:
    paths:
      - 'trial.cfg'
      - 'check_links.py'
      - '.github/workflows/check_links.yml'
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run check script
        env:
          TZ: 'Asia/Shanghai'
        run: python check_links.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add trial.cfg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update trial.cfg: Filtered invalid links [skip ci]" && git push)

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
